base_config:
  - train_v1_stage1.yaml
  - naf_baseline_common.yaml

stage:
  name: naf32_stage1
  objective: single_degradation_pretraining
  init_from_stage: null

experiment:
  name: naf32_stage1
  output_dir: experiments/naf32_stage1

model:
  base_channels: 32

runtime:
  checkpoint_dir: /root/autodl-tmp/DSD-Restor-checkpoints/naf32_stage1
  init_checkpoint: null
  tensorboard:
    run_name: naf32_stage1
